### ISSUE TITLE
Unable to build on Debian 11 Bullseye

### ISSUE THREAD

**Issue by ClaudeMa** [nwdigitalradio/paclink-unix#3]
Try to build on a fresh install Debian 11 Bullseye

./configure fail with
_checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GMIME... no
checking for GMIME... no
checking for GMIME... no
configure: error: in `/home/claude/src/paclink-unix':
configure: error: gmime-2.4.3 or newer not found_

On Debian 11 gmime is 3.2.7
cmd "pkg-config --modversion gmime-3.0" output
3.2.7
no gmime-2 available

**Comment by n7nix** [comment]
Need to install all current build requirements.
What do you see when you install the latest gmime library

apt-get install -y libgmime-3.0-dev

Make sure other libraries are also current.

apt-get update
apt-get install build-essential autoconf automake libtool
apt-get install postfix libdb-dev libglib2.0-0 zlib1g-dev libncurses5-dev libdb5.3-dev libgmime-3.0-dev

**Comment by n7nix** [comment]
I made a one line change to configure.ac to get past config and start to build.

-                PKG_CHECK_MODULES(GMIME, gmime-2.6 >= 2.4.3, , AC_MSG_FAILURE([gmime-2.4.3 or newer not found]))
+                PKG_CHECK_MODULES(GMIME, gmime-3.0 >= 2.4.3, , AC_MSG_FAILURE([gmime-2.4.3 or newer not found]))

However there are MANY differences between gmime 2.6 & 3.x libraries. I
had to modify the 7 files listed below to get paclink-unix to build.

   mail.wl2k.c
   mime2wl.c
   wl2kax25.c
   wl2kax25d.c
   wl2kserial.c
   wl2ktelnet.c
   wl2mime.c

I have not checked-in any of the changes I made to build with gmime
3.2.7 as that will obviously break Debian buster.

I need to take some time to understand the best way to maintain
compatibility between gmime 2.6 and gmime 3.0.

**Comment by n7nix** [comment]
I checked in changes to handle the new gmime 3.2.7 library as well as
being compatible with the gmime 2.6 library.

https://github.com/nwdigitalradio/paclink-unix/commit/df27a75dc267cbb3628fdca373d2b601fafe8a59

I have verified that the original gmime 2.6 library still works but I
haven't verified the gmime 3.0 changes other than it now builds with
Debian Bullseye/sid.
I will verify functionality on Bullseye in the next few days.

/Basil

**Comment by n7nix** [comment]
More work needs to be done on the the port to gmime 3.0.

While the last code changes allow paclink-unix to build with gmime 3.0
it segfaults in mime2wl. As of now paclink-unix will not run on Debian
Bullseye/sid.

**Comment by n7nix** [comment]
With the latest changes to _configure.ac_ paclink-unix now builds and runs on bullseye/sid.
You must install libgmime-2.6 and not use libgmime-3.0
```
sudo apt-get install libgmime-2.6-dev
```
configure.ac will build with the older gmime 2.6 library which giving me time to port the gmime code to gmime 3.0

**Comment by Levitator1** [comment]
Done fixed it. Yup.

**Comment by Levitator1** [comment]
Hrm. It works for receive, but it occurs to me I haven't tried sending mail yet. I'm trying to figure out how to do that so I can see whether there's a corresponding segfault or error when sending...

Jose
------- Original Message -------

**Comment by Levitator1** [comment]
Looks like you have to integrate with sendmail to get transmit working, and so that is more like a system-level install. At this point, I think I will work on a Debian package to manage installation and removal, and then I'll go back to testing transmit.
