### ISSUE TITLE
Error building on Ubuntu 20.04

### ISSUE THREAD

**Issue by frspin** [nwdigitalradio/paclink-unix#4]
There in an error in finding db.h file on Ubuntu 20.04
Configure script search db.h file in:

`
checking for /usr/pkg/include/db4/db.h... no
checking for /usr/pkg/include/db3/db.h... no
checking for db.h... no
`
but this file is installed in /usr/include and for 5.x version.

-rw-r--r-- 1 root root 123102 mar 21  2020 /usr/include/db.h

No change using --with-dbd-dir option in configure and with /usr or /usr/include ad DB install directory

Regards

Franco Spinelli
IW2DHW

**Comment by n7nix** [comment]
I have an Ubuntu 20.04 instance and am not seeing that problem.
Could you please do the following and see if this is a fix for you.

sudo apt-get install build-essential autoconf automake libtool
sudo apt-get install postfix libdb-dev libglib2.0-0 zlib1g-dev libncurses5-dev libdb5.3-dev libgmime-3.0-dev

Also are you using the buildall.sh script?

However when paclink-unix does build it will not run on Debian
Bullseye/sid because of work required to port from libgmime 2.6 to
libgmime 3.0.

See issue #3, Unable to build on Debian 11 Bullseye #3
https://github.com/nwdigitalradio/paclink-unix/issues/3

**Comment by n7nix** [comment]
> All of this apt commands give no update.

OK, thanks

> Sorry for italian language in comman output:

No worries.

> sudo apt-get install build-essential autoconf automake libtool
> sudo apt-get install postfix libdb-dev libglib2.0-0 zlib1g-dev libncurses5-dev libdb5.3-dev libgmime-3.0-dev
>
>> Also are you using the buildall.sh script?
>
> Yes. This is output from buildall.sh clean script:

OK, thanks, would like to see the last few lines of build_error.out
Also grep build_error.out & build_log.out for db.h

grep -i "db\.h" build_error.out
grep -i "db\.h" build_log.out

> and, configuring with ./configure, give me error in db.h file

Trying to determine how our 2 systems are different, why you see this
problem & I don't. Working on it.

> In Ubuntu 20.04 there is libgimime 2.6 and libgmime 3.0

Thanks for that. I will try to make a build that forces using libgmime
2.6 until I can finish the libgmime 3.0 port.

**Comment by frspin** [comment]
Il 01/10/21 17:55, Basil Gunn ha scritto:
> 
> grep -i "db\.h" build_error.out

No output from this grep

> grep -i "db\.h" build_log.out

checking for /usr/pkg/include/db4/db.h... no
checking for /usr/pkg/include/db3/db.h... no
checking for /usr/include/db.h... yes
checking for db.h... no

> 
> Trying to determine how our 2 systems are different, why you see this
> problem & I don't. Working on it.
> 
>> In Ubuntu 20.04 there is libgimime 2.6 and libgmime 3.0
> 
> Thanks for that. I will try to make a build that forces using libgmime
> 2.6 until I can finish the libgmime 3.0 port.
> 

Regards

Franco Spinelli
IW2DHW

**Comment by n7nix** [comment]
>> grep -i "db\.h" build_log.out
>
> checking for /usr/pkg/include/db4/db.h... no
> checking for /usr/pkg/include/db3/db.h... no
> checking for /usr/include/db.h... yes
> checking for db.h... no

Ok, thanks. I have the following from a fresh clone of the repo for
comparison.

git clone https://github.com/nwdigitalradio/paclink-unix
cd paclink-unix/
./buildall.sh 

$ grep -i "db\.h" build_error.out 
$ grep -i "db\.h" build_log.out 
checking for /usr/pkg/include/db4/db.h... no
checking for /usr/pkg/include/db3/db.h... no
checking for db.h... 5.3.28
checking netdb.h usability... yes
checking netdb.h presence... yes
checking for netdb.h... yes

Please check for which Berkeley DB is installed on your system (edited output)

$ dpkg -l "libdb*"

ii  libdb-dev:amd64          1:5.3.21~exp1ubuntu2            amd64        Berkeley Database Libraries [development]
ii  libdb5.3:amd64           5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3-dev             5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [development]

ii  libdbus-1-3:amd64        1.12.16-2ubuntu2.1              amd64        simple interprocess messaging system (library)
ii  libdbus-glib-1-2:amd64   0.110-5fakssync1                amd64        deprecated library for D-Bus IPC
ii  libdbusmenu-glib4:amd64  16.04.1+18.10.20180917-0ubuntu6 amd64        library for passing menus over DBus
ii  libdbusmenu-gtk3-4:amd64 16.04.1+18.10.20180917-0ubuntu6 amd64        library for passing menus over DBus - GTK+ version

**Comment by frspin** [comment]
Il 01/10/21 18:09, Basil Gunn ha scritto:
> 
>>> grep -i "db\.h" build_log.out
>>
>> checking for /usr/pkg/include/db4/db.h... no
>> checking for /usr/pkg/include/db3/db.h... no
>> checking for /usr/include/db.h... yes
>> checking for db.h... no
> 
> Ok, thanks. I have the following from a fresh clone of the repo for
> comparison.
> 
> git clone https://github.com/nwdigitalradio/paclink-unix
> cd paclink-unix/
> ./buildall.sh
> 
> $ grep -i "db\.h" build_error.out
> $ grep -i "db\.h" build_log.out
> checking for /usr/pkg/include/db4/db.h... no
> checking for /usr/pkg/include/db3/db.h... no
> checking for db.h... 5.3.28
> checking netdb.h usability... yes
> checking netdb.h presence... yes
> checking for netdb.h... yes
> 
I have also tried with a fresh git clone, without any difference

> Please check for which Berkeley DB is installed on your system (edited
> output)
> 
> $ dpkg -l "libdb*"
> 
> ii libdb-dev:amd64 1:5.3.21~exp1ubuntu2 amd64 Berkeley Database
> Libraries [development]
> ii libdb5.3:amd64 5.3.28+dfsg1-0.6ubuntu2 amd64 Berkeley v5.3 Database
> Libraries [runtime]
> ii libdb5.3-dev 5.3.28+dfsg1-0.6ubuntu2 amd64 Berkeley v5.3 Database
> Libraries [development]
> 

Many DB versions as:

ii  libdb++-dev:amd64        1:5.3.21~exp1ubuntu2            amd64
  ii  libdb-dev:amd64          1:5.3.21~exp1ubuntu2            amd64
    un  libdb4.6++-dev           <nessuna>
<nessuna>    un  libdb4.6-dev             <nessuna>
  <nessuna>    un  libdb4.7++-dev           <nessuna>
    <nessuna>    un  libdb4.7-dev             <nessuna>
      <nessuna>    un  libdb4.8++-dev           <nessuna>
        <nessuna>    un  libdb4.8-dev             <nessuna>
          <nessuna>    un  libdb5.1++-dev           <nessuna>
            <nessuna>    un  libdb5.1-dev             <nessuna>
              <nessuna>    un  libdb5.2++-dev           <nessuna>
                <nessuna>    un  libdb5.2-dev             <nessuna>
                  <nessuna>    ii  libdb5.3:amd64
5.3.28+dfsg1-0.6ubuntu2         amd64        ii  libdb5.3:i386
  5.3.28+dfsg1-0.6ubuntu2         i386         ii  libdb5.3++:amd64
    5.3.28+dfsg1-0.6ubuntu2         amd64        ii  libdb5.3++-dev
      5.3.28+dfsg1-0.6ubuntu2         amd64        ii  libdb5.3-dev
        5.3.28+dfsg1-0.6ubuntu2         amd64        un
libdbd-anydata-perl      <nessuna>                       <nessuna>    un
 libdbd-csv-perl          <nessuna>                       <nessuna>
ii  libdbd-pg-perl           3.10.4-1                        amd64

Regards

Franco Spinelli
IW2DHW

**Comment by n7nix** [comment]
File db.h is in package libdb5.3-dev

See if db.h file already exists:
(Is this a build problem or an install problem?)

ls -alt /usr/include/db.h

Try reinstalling the libdb5.3-dev package

sudo apt-get install --reinstall libdb5.3-dev

**Comment by frspin** [comment]
Il 01/10/21 18:42, Basil Gunn ha scritto:
> 
> File db.h is in package libdb5.3-dev
> 
> See if db.h file already exists:
> (Is this a build problem or an install problem?)
> 
> ls -alt /usr/include/db.h

***@***.***:/mnt/Prog/ham$ ls -alt /usr/include/db.h
-rw-r--r-- 1 root root 123102 mar 21  2020 /usr/include/db.h

> 
> Try reinstalling the libdb5.3-dev package
> 
> sudo apt-get install --reinstall libdb5.3-dev

Done

I also done a fresh clone of GIT repo, as in your previous mail and
after this a buildall.sh clean

***@***.***:/mnt/Prog/ham/paclink-unix$ ./buildall.sh clean
Starting build from clean
=== building paclink-unix for MTA: postfix
This will take a few minutes, output is captured to
/mnt/Prog/ham/paclink-unix/build_log.out
=== start from distclean
=== running autotools
=== running configure
build failed at configure

But no change, same error

***@***.***:/mnt/Prog/ham/paclink-unix$ grep -i "db\.h" build_log.out
checking for /usr/pkg/include/db4/db.h... no
checking for /usr/pkg/include/db3/db.h... no
checking for db.h... no

Regards

Franco Spinelli
IW2DHW

**Comment by n7nix** [comment]
Autotools (./configure script) is confused about which Berkeley database
library is installed or is defaulting to the wrong one required by
paclink-unix.

Since you are using multiarch there is one package you are missing.

apt-get install libdb5.3-dev:i386

You should see all the following packages installed for your config.

 dpkg -l "libdb*"
 
ii  libdb5.3:amd64           5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3-dev             5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [development]
ii  libdb5.3:amd64           5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3:i386            5.3.28+dfsg1-0.6ubuntu2         i386         Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3++:amd64         5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries for C++ [runtime]
ii  libdb5.3-dev:i386        5.3.28+dfsg1-0.6ubuntu2         i386         Berkeley v5.3 Database Libraries [development]

**Comment by n7nix** [comment]
>> apt-get install libdb5.3-dev:i386
>
> With this command I get a message for removing libdb-dev libdb5.3-dev

From where? What app were you running?
See below for which libraries worked for me.

> and this is what I don't want!
> libdb5.3-dev and libdb5.3-dev:i386 are mutually exclusive

I believe apt is warning you have some multiarch dependencies which
can't be met.

Not sure what you are trying to accomplish.  I was able to build
paclink-unix with the following installed db5 libraries. Why not try
just installing (reinstalling) these libs and see if you can't get it to
work.

ii  libdb-dev:amd64          1:5.3.21~exp1ubuntu2            amd64        Berkeley Database Libraries [development]
ii  libdb5.3:amd64           5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3-dev             5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [development]
ii  libdb5.3:amd64           5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3:i386            5.3.28+dfsg1-0.6ubuntu2         i386         Berkeley v5.3 Database Libraries [runtime]
ii  libdb5.3++:amd64         5.3.28+dfsg1-0.6ubuntu2         amd64        Berkeley v5.3 Database Libraries for C++ [runtime]
ii  libdb5.3-dev:i386        5.3.28+dfsg1-0.6ubuntu2         i386         Berkeley v5.3 Database Libraries [development]

You might also try remove-architecture i386 and add-architecture i386

By the way, I have paclink-unix building/running on bullseye/sid by
building with libgmime-2.6.

**Comment by frspin** [comment]
Il 01/10/21 20:29, Basil Gunn ha scritto:
> 
>>> apt-get install libdb5.3-dev:i386
>>
>> With this command I get a message for removing libdb-dev libdb5.3-dev
> 
> From where? What app were you running?
> See below for which libraries worked for me.

This is message from command, as usual in italian language

***@***.***:/mnt/Prog/ham/paclink-unix$ sudo apt-get install
libdb5.3-dev:i386
Lettura elenco dei pacchetti... Fatto
Generazione albero delle dipendenze
Lettura informazioni sullo stato... Fatto
Pacchetti suggeriti:
  db5.3-doc:i386
I seguenti pacchetti saranno RIMOSSI:
  libdb5.3-dev
I seguenti pacchetti NUOVI saranno installati:
  libdb5.3-dev:i386
0 aggiornati, 1 installati, 1 da rimuovere e 0 non aggiornati.
È necessario scaricare 0 B/849 kB di archivi.
Dopo quest'operazione, verranno liberati 185 kB di spazio su disco.
Continuare? [S/n]


> 
> I believe apt is warning you have some multiarch dependencies which
> can't be met.
> 
> Not sure what you are trying to accomplish. I was able to build
> paclink-unix with the following installed db5 libraries. Why not try
> just installing (reinstalling) these libs and see if you can't get it to
> work.

Already done, without any change.

> 
> ii libdb-dev:amd64 1:5.3.21~exp1ubuntu2 amd64 Berkeley Database
> Libraries [development]
> ii libdb5.3:amd64 5.3.28+dfsg1-0.6ubuntu2 amd64 Berkeley v5.3 Database
> Libraries [runtime]
> ii libdb5.3-dev 5.3.28+dfsg1-0.6ubuntu2 amd64 Berkeley v5.3 Database
> Libraries [development]
> ii libdb5.3:amd64 5.3.28+dfsg1-0.6ubuntu2 amd64 Berkeley v5.3 Database
> Libraries [runtime]
> ii libdb5.3:i386 5.3.28+dfsg1-0.6ubuntu2 i386 Berkeley v5.3 Database
> Libraries [runtime]
> ii libdb5.3++:amd64 5.3.28+dfsg1-0.6ubuntu2 amd64 Berkeley v5.3 Database
> Libraries for C++ [runtime]
> ii libdb5.3-dev:i386 5.3.28+dfsg1-0.6ubuntu2 i386 Berkeley v5.3 Database
> Libraries [development]
> 
> You might also try remove-architecture i386 and add-architecture i386

i386 architecture is required from wine and some other program.
I will try removing and re-adding this architecture

> 
> By the way, I have paclink-unix building/running on bullseye/sid by
> building with libgmime-2.6.

After this:
***@***.***:/mnt/Prog/ham/paclink-unix$ git pull
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 6 (delta 4), reused 6 (delta 4), pack-reused 0
Decompressione degli oggetti in corso: 100% (6/6), 782 byte | 156.00
KiB/s, fatto.
Da https://github.com/nwdigitalradio/paclink-unix
   df27a75..f3ec5ec  master     -> origin/master
Aggiornamento di df27a75..f3ec5ec
Fast-forward
 configure.ac | 2 ++
 mime2wl.c    | 4 ++++
 2 files changed, 6 insertions(+)


for libgmime-2.6 I redo buildall.sh clear command and now all is working

=== building paclink-unix for MTA: postfix
This will take a few minutes, output is captured to
/mnt/Prog/ham/paclink-unix/build_log.out
=== running autotools
=== running configure
=== making paclink-unix using 4 cores
=== installing paclink-unix
=== verifying paclink-unix install
Check for required installed files ... OK

2021 10 01 21:07:36 CEST: paclink-unix build script FINISHED

and make; sudo make install do the job

What was changed? A GIT problem in clone command?

Regards

Franco Spinelli
IW2DHW

**Comment by n7nix** [comment]
> for libgmime-2.6 I redo buildall.sh clear command and now all is working
>
> === building paclink-unix for MTA: postfix
> This will take a few minutes, output is captured to
> /mnt/Prog/ham/paclink-unix/build_log.out
> === running autotools
> === running configure
> === making paclink-unix using 4 cores
> === installing paclink-unix
> === verifying paclink-unix install
> Check for required installed files ... OK
>
> 2021 10 01 21:07:36 CEST: paclink-unix build script FINISHED
>
> and make; sudo make install do the job

buildall.sh script does make & make install so should not have to that
again.

> What was changed? A GIT problem in clone command?

To list the last 5 commits run the following git command in the
paclink-unix directory:

$ git show HEAD~5..HEAD

**Comment by frspin** [comment]
Il 01/10/21 21:46, Basil Gunn ha scritto:
> 
> 
> buildall.sh script does make & make install so should not have to that
> again.

I have run buildall.sh as user so I need to do install as root.

> 
>> What was changed? A GIT problem in clone command?
> 
> To list the last 5 commits run the following git command in the
> paclink-unix directory:
> 
> $ git show HEAD~5..HEAD
> 

This command show changes in configure.ac, related to libgmime version,
so nothing related to db.h

Regards

Franco Spinelli
IW2DHW

**Comment by n7nix** [comment]
> I have run buildall.sh as user so I need to do install as root.

buildall.sh script was meant to run as user. You do NOT need to run:
make; sudo make install
after running the buildall.sh script.

Snippet from buildall.sh script:

   echo "=== installing paclink-unix"
   sudo make install >> build_log.out 2>> build_error.out
   if [ "$?" -ne 0 ] ; then echo "build failed at make install"; exit 1; fi

>>> What was changed? A GIT problem in clone command?
>> 
>> To list the last 5 commits run the following git command in the
>> paclink-unix directory:
>> 
>> $ git show HEAD~5..HEAD
>
> This command show changes in configure.ac, related to libgmime version,
> so nothing related to db.h

You asked what changed. That command shows the last 5 commits for the
following files:
diff --git a/configure.ac b/configure.ac
    Add comment for libgmime 3.x differences
diff --git a/mime2wl.c b/mime2wl.c
diff --git a/ChangeLog b/ChangeLog
diff --git a/configure.ac b/configure.ac
diff --git a/mail.wl2k.c b/mail.wl2k.c
diff --git a/mime2wl.c b/mime2wl.c
diff --git a/wl2kax25.c b/wl2kax25.c
diff --git a/wl2kax25d.c b/wl2kax25d.c
diff --git a/wl2kserial.c b/wl2kserial.c
diff --git a/wl2ktelnet.c b/wl2ktelnet.c
diff --git a/wl2mime.c b/wl2mime.c
diff --git a/test_scripts/chk_perm.sh b/test_scripts/chk_perm.sh

I believe running: apt-get install libdb5.3-dev:i386
solved your db.h problem.

**Comment by frspin** [comment]
Il 02/10/21 23:55, Basil Gunn ha scritto:
> 
>> I have run buildall.sh as user so I need to do install as root.
> 
> buildall.sh script was meant to run as user. You do NOT need to run:
> make; sudo make install
> after running the buildall.sh script.
> 
> Snippet from buildall.sh script:
> 
> echo "=== installing paclink-unix"
> sudo make install >> build_log.out 2>> build_error.out
> if [ "$?" -ne 0 ] ; then echo "build failed at make install"; exit 1; fi
> 

Understood

> 
> You asked what changed. That command shows the last 5 commits for the
> following files:
> diff --git a/configure.ac b/configure.ac
> Add comment for libgmime 3.x differences
> diff --git a/mime2wl.c b/mime2wl.c
> diff --git a/ChangeLog b/ChangeLog
> diff --git a/configure.ac b/configure.ac
> diff --git a/mail.wl2k.c b/mail.wl2k.c
> diff --git a/mime2wl.c b/mime2wl.c
> diff --git a/wl2kax25.c b/wl2kax25.c
> diff --git a/wl2kax25d.c b/wl2kax25d.c
> diff --git a/wl2kserial.c b/wl2kserial.c
> diff --git a/wl2ktelnet.c b/wl2ktelnet.c
> diff --git a/wl2mime.c b/wl2mime.c
> diff --git a/test_scripts/chk_perm.sh b/test_scripts/chk_perm.sh
> 
> I believe running: apt-get install libdb5.3-dev:i386
> solved your db.h problem.

Now the problem is solved even if it is not clear why.
So you can close this issue

Thank you very much

Franco Spinelli
IW2DHW
